-- ============================================================
-- AIRA POC-1 Phase 1
-- Identity Core Tables
-- Generated by POC-1 Build Phase 1 script
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS aira_security;

CREATE TABLE IF NOT EXISTS aira_security.institution (
    institution_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    institution_key VARCHAR(120) NOT NULL UNIQUE,
    institution_name VARCHAR(240) NOT NULL,
    institution_type VARCHAR(80) NOT NULL,
    institution_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    primary_domain VARCHAR(240) UNIQUE,
    country_code VARCHAR(10),
    timezone_name VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.institution_domain (
    domain_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    institution_id UUID NOT NULL REFERENCES aira_security.institution(institution_id),
    domain_name VARCHAR(240) NOT NULL UNIQUE,
    domain_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    auto_match_allowed BOOLEAN NOT NULL DEFAULT TRUE,
    approval_required BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.platform_identity (
    identity_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    institution_id UUID REFERENCES aira_security.institution(institution_id),
    email VARCHAR(320) NOT NULL UNIQUE,
    normalized_email VARCHAR(320) NOT NULL UNIQUE,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    display_name VARCHAR(240) NOT NULL,
    department VARCHAR(160),
    job_title VARCHAR(160),
    requested_role VARCHAR(80),
    identity_status VARCHAR(60) NOT NULL DEFAULT 'PENDING_EMAIL_VERIFICATION',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    institution_approved BOOLEAN NOT NULL DEFAULT FALSE,
    governance_terms_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.platform_identity_credential (
    credential_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID NOT NULL REFERENCES aira_security.platform_identity(identity_id),
    credential_type VARCHAR(40) NOT NULL DEFAULT 'PASSWORD',
    password_hash TEXT NOT NULL,
    password_algorithm VARCHAR(80) NOT NULL DEFAULT 'BCRYPT',
    password_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    password_changed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_email_verification (
    verification_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID NOT NULL REFERENCES aira_security.platform_identity(identity_id),
    token_hash TEXT NOT NULL UNIQUE,
    verification_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    verification_channel VARCHAR(40) NOT NULL DEFAULT 'EMAIL',
    sent_to_email VARCHAR(320) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_access_request (
    access_request_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID NOT NULL REFERENCES aira_security.platform_identity(identity_id),
    requested_institution_key VARCHAR(120),
    requested_institution_id UUID REFERENCES aira_security.institution(institution_id),
    requested_role VARCHAR(80) NOT NULL,
    request_reason TEXT,
    request_status VARCHAR(60) NOT NULL DEFAULT 'PENDING_EMAIL_VERIFICATION',
    email_verified_at TIMESTAMPTZ,
    reviewed_by_identity_id UUID REFERENCES aira_security.platform_identity(identity_id),
    reviewed_at TIMESTAMPTZ,
    approval_decision VARCHAR(40),
    approval_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_role_assignment (
    role_assignment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID NOT NULL REFERENCES aira_security.platform_identity(identity_id),
    institution_id UUID NOT NULL REFERENCES aira_security.institution(institution_id),
    role_key VARCHAR(80) NOT NULL,
    assignment_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    assigned_by_identity_id UUID REFERENCES aira_security.platform_identity(identity_id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_identity_role_assignment UNIQUE (identity_id, institution_id, role_key)
);

CREATE TABLE IF NOT EXISTS aira_security.identity_permission_catalog (
    permission_key VARCHAR(120) PRIMARY KEY,
    permission_name VARCHAR(240) NOT NULL,
    permission_category VARCHAR(120) NOT NULL,
    permission_description TEXT NOT NULL,
    permission_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_role_permission (
    role_permission_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role_key VARCHAR(80) NOT NULL,
    permission_key VARCHAR(120) NOT NULL REFERENCES aira_security.identity_permission_catalog(permission_key),
    mapping_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_identity_role_permission UNIQUE (role_key, permission_key)
);

CREATE TABLE IF NOT EXISTS aira_security.identity_session (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID NOT NULL REFERENCES aira_security.platform_identity(identity_id),
    institution_id UUID NOT NULL REFERENCES aira_security.institution(institution_id),
    session_token_hash TEXT NOT NULL UNIQUE,
    session_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ,
    logout_at TIMESTAMPTZ,
    client_ip VARCHAR(80),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_login_audit (
    login_audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID REFERENCES aira_security.platform_identity(identity_id),
    institution_id UUID REFERENCES aira_security.institution(institution_id),
    normalized_email VARCHAR(320),
    event_type VARCHAR(80) NOT NULL,
    event_result VARCHAR(40) NOT NULL,
    denial_reason VARCHAR(160),
    client_ip VARCHAR(80),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_approval_audit (
    approval_audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    access_request_id UUID NOT NULL REFERENCES aira_security.identity_access_request(access_request_id),
    target_identity_id UUID NOT NULL REFERENCES aira_security.platform_identity(identity_id),
    reviewer_identity_id UUID NOT NULL REFERENCES aira_security.platform_identity(identity_id),
    institution_id UUID NOT NULL REFERENCES aira_security.institution(institution_id),
    action_type VARCHAR(80) NOT NULL,
    action_result VARCHAR(40) NOT NULL,
    role_key VARCHAR(80),
    approval_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_notification_outbox (
    notification_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id UUID REFERENCES aira_security.platform_identity(identity_id),
    institution_id UUID REFERENCES aira_security.institution(institution_id),
    notification_type VARCHAR(120) NOT NULL,
    notification_channel VARCHAR(40) NOT NULL DEFAULT 'EMAIL',
    recipient_email VARCHAR(320) NOT NULL,
    subject TEXT NOT NULL,
    body_template_key VARCHAR(160) NOT NULL,
    safe_message_summary TEXT,
    notification_status VARCHAR(40) NOT NULL DEFAULT 'QUEUED',
    queued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_institution_status ON aira_security.institution(institution_status);
CREATE INDEX IF NOT EXISTS idx_institution_domain_institution ON aira_security.institution_domain(institution_id);
CREATE INDEX IF NOT EXISTS idx_platform_identity_institution ON aira_security.platform_identity(institution_id);
CREATE INDEX IF NOT EXISTS idx_platform_identity_status ON aira_security.platform_identity(identity_status);
CREATE INDEX IF NOT EXISTS idx_access_request_status ON aira_security.identity_access_request(request_status);
CREATE INDEX IF NOT EXISTS idx_role_assignment_identity ON aira_security.identity_role_assignment(identity_id);
CREATE INDEX IF NOT EXISTS idx_role_assignment_institution ON aira_security.identity_role_assignment(institution_id);
CREATE INDEX IF NOT EXISTS idx_identity_session_identity ON aira_security.identity_session(identity_id);
CREATE INDEX IF NOT EXISTS idx_identity_session_status ON aira_security.identity_session(session_status);
CREATE INDEX IF NOT EXISTS idx_login_audit_identity ON aira_security.identity_login_audit(identity_id);
CREATE INDEX IF NOT EXISTS idx_login_audit_event_type ON aira_security.identity_login_audit(event_type);
CREATE INDEX IF NOT EXISTS idx_notification_outbox_status ON aira_security.identity_notification_outbox(notification_status);

COMMENT ON TABLE aira_security.institution IS 'POC-1 institution or tenant records.';
COMMENT ON TABLE aira_security.platform_identity IS 'POC-1 user identity records.';
COMMENT ON TABLE aira_security.identity_access_request IS 'POC-1 signup and request access workflow records.';
COMMENT ON TABLE aira_security.identity_session IS 'POC-1 authenticated identity sessions.';
COMMENT ON TABLE aira_security.identity_notification_outbox IS 'POC-1 notification queue for email verification and access request lifecycle messages.';