-- ============================================================
-- AIRA POC-1 Phase 1
-- Identity Microfunction Tables
-- Generated by POC-1 Build Phase 1 script
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS aira_security;

CREATE TABLE IF NOT EXISTS aira_security.identity_microfunction_catalog (
    microfunction_key VARCHAR(120) PRIMARY KEY,
    microfunction_name VARCHAR(240) NOT NULL,
    microfunction_category VARCHAR(120) NOT NULL,
    microfunction_description TEXT NOT NULL,
    owning_module VARCHAR(120) NOT NULL,
    execution_phase VARCHAR(120) NOT NULL,
    fail_closed_required BOOLEAN NOT NULL DEFAULT TRUE,
    audit_required BOOLEAN NOT NULL DEFAULT TRUE,
    evidence_required BOOLEAN NOT NULL DEFAULT TRUE,
    microfunction_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS aira_security.identity_microfunction_execution (
    execution_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    microfunction_key VARCHAR(120) NOT NULL REFERENCES aira_security.identity_microfunction_catalog(microfunction_key),
    identity_id UUID REFERENCES aira_security.platform_identity(identity_id),
    institution_id UUID REFERENCES aira_security.institution(institution_id),
    access_request_id UUID REFERENCES aira_security.identity_access_request(access_request_id),
    session_id UUID REFERENCES aira_security.identity_session(session_id),
    correlation_id VARCHAR(160) NOT NULL,
    execution_status VARCHAR(40) NOT NULL,
    input_summary TEXT,
    output_summary TEXT,
    failure_reason TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_identity_microfunction_category ON aira_security.identity_microfunction_catalog(microfunction_category);
CREATE INDEX IF NOT EXISTS idx_identity_microfunction_status ON aira_security.identity_microfunction_catalog(microfunction_status);
CREATE INDEX IF NOT EXISTS idx_identity_microfunction_execution_key ON aira_security.identity_microfunction_execution(microfunction_key);
CREATE INDEX IF NOT EXISTS idx_identity_microfunction_execution_identity ON aira_security.identity_microfunction_execution(identity_id);
CREATE INDEX IF NOT EXISTS idx_identity_microfunction_execution_institution ON aira_security.identity_microfunction_execution(institution_id);
CREATE INDEX IF NOT EXISTS idx_identity_microfunction_execution_correlation ON aira_security.identity_microfunction_execution(correlation_id);
CREATE INDEX IF NOT EXISTS idx_identity_microfunction_execution_status ON aira_security.identity_microfunction_execution(execution_status);

COMMENT ON TABLE aira_security.identity_microfunction_catalog IS 'POC-1 governed identity microfunction catalog.';
COMMENT ON TABLE aira_security.identity_microfunction_execution IS 'POC-1 identity microfunction execution audit and evidence support records.';