-- ============================================================
-- AIRA POC-1 Phase 1
-- Identity Seed Data + Microfunction Catalog
-- Generated by POC-1 Build Phase 1 script
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS aira_security;

INSERT INTO aira_security.institution
(institution_key, institution_name, institution_type, institution_status, primary_domain, country_code, timezone_name)
VALUES
('AIRA-DEMO-INSTITUTION', 'AIRA Demo Institution', 'INTERNAL', 'ACTIVE', 'aira.local', 'PH', 'Asia/Manila')
ON CONFLICT (institution_key) DO UPDATE SET
    institution_name = EXCLUDED.institution_name,
    institution_type = EXCLUDED.institution_type,
    institution_status = EXCLUDED.institution_status,
    primary_domain = EXCLUDED.primary_domain,
    country_code = EXCLUDED.country_code,
    timezone_name = EXCLUDED.timezone_name,
    updated_at = NOW();

INSERT INTO aira_security.institution_domain
(institution_id, domain_name, domain_status, auto_match_allowed, approval_required)
SELECT institution_id, 'aira.local', 'ACTIVE', true, true
FROM aira_security.institution
WHERE institution_key = 'AIRA-DEMO-INSTITUTION'
ON CONFLICT (domain_name) DO UPDATE SET
    domain_status = EXCLUDED.domain_status,
    auto_match_allowed = EXCLUDED.auto_match_allowed,
    approval_required = EXCLUDED.approval_required,
    updated_at = NOW();

-- POC-1 permission catalog seed data
INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_PORTAL', 'View Portal', 'PORTAL', 'Allows user to view authenticated portal home and public-safe authenticated status.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_AGENT_REGISTRY', 'View Agent Registry', 'AGENTS', 'Allows user to view governed AIRA agent registry information.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_GOVERNANCE', 'View Governance', 'GOVERNANCE', 'Allows user to view governance readiness and control gate information.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_EVIDENCE', 'View Evidence', 'EVIDENCE', 'Allows user to view assigned evidence and evidence readiness records.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_RELEASE_READINESS', 'View Release Readiness', 'GOVERNANCE', 'Allows user to view release readiness state.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_APPLICATION_FACTORY', 'View Application Factory', 'FACTORY', 'Allows user to view Application Factory capabilities and readiness.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('MANAGE_ACCESS_REQUESTS', 'Manage Access Requests', 'SECURITY', 'Allows institution admin to approve or reject access requests.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('MANAGE_ROLE_ASSIGNMENTS', 'Manage Role Assignments', 'SECURITY', 'Allows institution admin to assign institution-scoped roles.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_SECURITY_AUDIT', 'View Security Audit', 'SECURITY', 'Allows user to view security and access audit records.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_permission_catalog
(permission_key, permission_name, permission_category, permission_description, permission_status)
VALUES ('VIEW_LOGIN_AUDIT', 'View Login Audit', 'SECURITY', 'Allows user to view login audit records.', 'ACTIVE')
ON CONFLICT (permission_key) DO UPDATE SET
    permission_name = EXCLUDED.permission_name,
    permission_category = EXCLUDED.permission_category,
    permission_description = EXCLUDED.permission_description,
    permission_status = EXCLUDED.permission_status,
    updated_at = NOW();

-- POC-1 role-permission seed data
INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_PORTAL', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_AGENT_REGISTRY', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_GOVERNANCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_EVIDENCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_RELEASE_READINESS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_APPLICATION_FACTORY', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'MANAGE_ACCESS_REQUESTS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'MANAGE_ROLE_ASSIGNMENTS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_SECURITY_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('PLATFORM_ADMIN', 'VIEW_LOGIN_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_PORTAL', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_AGENT_REGISTRY', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_GOVERNANCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_EVIDENCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_RELEASE_READINESS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_APPLICATION_FACTORY', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'MANAGE_ACCESS_REQUESTS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'MANAGE_ROLE_ASSIGNMENTS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_SECURITY_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('INSTITUTION_ADMIN', 'VIEW_LOGIN_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('DEVELOPER', 'VIEW_PORTAL', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('DEVELOPER', 'VIEW_AGENT_REGISTRY', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('DEVELOPER', 'VIEW_EVIDENCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('DEVELOPER', 'VIEW_APPLICATION_FACTORY', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('SECURITY_OFFICER', 'VIEW_PORTAL', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('SECURITY_OFFICER', 'VIEW_GOVERNANCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('SECURITY_OFFICER', 'VIEW_EVIDENCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('SECURITY_OFFICER', 'VIEW_SECURITY_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('SECURITY_OFFICER', 'VIEW_LOGIN_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('AUDITOR', 'VIEW_PORTAL', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('AUDITOR', 'VIEW_GOVERNANCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('AUDITOR', 'VIEW_EVIDENCE', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('AUDITOR', 'VIEW_RELEASE_READINESS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('AUDITOR', 'VIEW_SECURITY_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('AUDITOR', 'VIEW_LOGIN_AUDIT', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('VIEWER', 'VIEW_PORTAL', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_role_permission
(role_key, permission_key, mapping_status)
VALUES ('VIEWER', 'VIEW_RELEASE_READINESS', 'ACTIVE')
ON CONFLICT (role_key, permission_key) DO UPDATE SET
    mapping_status = EXCLUDED.mapping_status,
    updated_at = NOW();

-- POC-1 identity microfunction catalog seed data
INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-001', 'ValidateSignupInput', 'SIGNUP', 'Validate submitted signup fields and required governance acceptance.', 'accelerator-security', 'SIGNUP', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-002', 'NormalizeEmailAddress', 'SIGNUP', 'Lowercase and canonicalize email address.', 'accelerator-security', 'SIGNUP', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-003', 'ResolveInstitutionFromDomain', 'SIGNUP', 'Match email domain or submitted institution key to institution.', 'accelerator-security', 'SIGNUP', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-004', 'CreatePendingIdentity', 'SIGNUP', 'Create identity with PENDING_EMAIL_VERIFICATION status.', 'accelerator-security', 'SIGNUP', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-005', 'HashIdentityPassword', 'SIGNUP', 'Hash submitted password using approved algorithm.', 'accelerator-security', 'SIGNUP', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-006', 'CreateAccessRequest', 'SIGNUP', 'Create request access workflow record.', 'accelerator-security', 'SIGNUP', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-007', 'CreateEmailVerificationToken', 'SIGNUP', 'Create single-use time-limited verification token.', 'accelerator-security', 'SIGNUP', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-008', 'QueueVerificationEmail', 'SIGNUP', 'Queue or send verification email.', 'accelerator-security', 'SIGNUP', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-009', 'RecordSignupAudit', 'SIGNUP', 'Record signup attempt and result.', 'accelerator-security', 'SIGNUP', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-010', 'CreateSignupEvidenceEvent', 'SIGNUP', 'Create evidence event for signup submission.', 'accelerator-security', 'SIGNUP', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-011', 'ValidateVerificationToken', 'VERIFICATION', 'Validate verification token hash, expiry, and status.', 'accelerator-security', 'EMAIL_VERIFICATION', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-012', 'ExpireOldVerificationTokens', 'VERIFICATION', 'Mark expired pending tokens as expired.', 'accelerator-security', 'EMAIL_VERIFICATION', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-013', 'MarkEmailVerified', 'VERIFICATION', 'Mark identity email_verified as true.', 'accelerator-security', 'EMAIL_VERIFICATION', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-014', 'MoveAccessRequestToPendingApproval', 'VERIFICATION', 'Move request to PENDING_INSTITUTION_APPROVAL.', 'accelerator-security', 'EMAIL_VERIFICATION', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-015', 'NotifyInstitutionAdmin', 'VERIFICATION', 'Notify institution admin of verified pending request.', 'accelerator-security', 'EMAIL_VERIFICATION', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-016', 'RecordVerificationAudit', 'VERIFICATION', 'Record verification attempt and result.', 'accelerator-security', 'EMAIL_VERIFICATION', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-017', 'CreateVerificationEvidenceEvent', 'VERIFICATION', 'Create evidence event for email verification.', 'accelerator-security', 'EMAIL_VERIFICATION', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-018', 'ListPendingAccessRequests', 'APPROVAL', 'List verified requests awaiting review.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-019', 'ValidateReviewerAuthority', 'APPROVAL', 'Confirm reviewer can approve for institution.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-020', 'ApproveAccessRequest', 'APPROVAL', 'Approve a verified access request.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-021', 'RejectAccessRequest', 'APPROVAL', 'Reject an access request.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-022', 'AssignInstitutionRole', 'APPROVAL', 'Assign institution-scoped role to identity.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-023', 'ActivateIdentity', 'APPROVAL', 'Mark identity ACTIVE after approval and role assignment.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-024', 'NotifyUserAccessApproved', 'APPROVAL', 'Notify user access is approved.', 'accelerator-security', 'INSTITUTION_APPROVAL', false, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-025', 'NotifyUserAccessRejected', 'APPROVAL', 'Notify user request update without sensitive policy detail.', 'accelerator-security', 'INSTITUTION_APPROVAL', false, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-026', 'RecordApprovalAudit', 'APPROVAL', 'Record approval or rejection audit event.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-027', 'CreateApprovalEvidenceEvent', 'APPROVAL', 'Create evidence event for approval decision.', 'accelerator-security', 'INSTITUTION_APPROVAL', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-028', 'ValidateLoginInput', 'LOGIN_SESSION', 'Validate email, password, and institution selector.', 'accelerator-security', 'LOGIN', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-029', 'LoadIdentityByEmail', 'LOGIN_SESSION', 'Load identity using normalized email.', 'accelerator-security', 'LOGIN', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-030', 'VerifyPassword', 'LOGIN_SESSION', 'Verify password against stored hash.', 'accelerator-security', 'LOGIN', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-031', 'CheckEmailVerified', 'LOGIN_SESSION', 'Block login if email is not verified.', 'accelerator-security', 'LOGIN', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-032', 'CheckInstitutionApproved', 'LOGIN_SESSION', 'Block login if institution approval is missing.', 'accelerator-security', 'LOGIN', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-033', 'CheckIdentityStatus', 'LOGIN_SESSION', 'Block login if identity is suspended, locked, rejected, or deactivated.', 'accelerator-security', 'LOGIN', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-034', 'CheckRoleAssignment', 'LOGIN_SESSION', 'Block login if no active role assignment exists.', 'accelerator-security', 'LOGIN', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-035', 'CreateIdentitySession', 'LOGIN_SESSION', 'Create governed active session.', 'accelerator-security', 'LOGIN', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-036', 'RecordLoginSuccessAudit', 'LOGIN_SESSION', 'Record successful login.', 'accelerator-security', 'LOGIN', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-037', 'RecordLoginFailureAudit', 'LOGIN_SESSION', 'Record failed login.', 'accelerator-security', 'LOGIN', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-038', 'IncrementFailedLoginCounter', 'LOGIN_SESSION', 'Increment failed login count.', 'accelerator-security', 'LOGIN', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-039', 'LockIdentityIfThresholdExceeded', 'LOGIN_SESSION', 'Lock identity when threshold is exceeded.', 'accelerator-security', 'LOGIN', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-040', 'LoadActiveSession', 'RBAC_LANDING', 'Load and validate active session.', 'accelerator-security', 'RBAC_LANDING', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-041', 'ResolveInstitutionContext', 'RBAC_LANDING', 'Resolve active institution context.', 'accelerator-security', 'RBAC_LANDING', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-042', 'ResolveRoleAssignments', 'RBAC_LANDING', 'Resolve active role assignments.', 'accelerator-security', 'RBAC_LANDING', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-043', 'ResolvePermissionSet', 'RBAC_LANDING', 'Resolve permissions from roles.', 'accelerator-security', 'RBAC_LANDING', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-044', 'ResolveLandingRoute', 'RBAC_LANDING', 'Select correct dashboard route.', 'accelerator-security', 'RBAC_LANDING', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-045', 'ValidateDashboardAccess', 'RBAC_LANDING', 'Validate access to requested dashboard.', 'accelerator-security', 'RBAC_LANDING', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-046', 'BlockUnauthorizedDashboard', 'RBAC_LANDING', 'Fail closed when dashboard is unauthorized.', 'accelerator-security', 'RBAC_LANDING', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-047', 'RecordUnauthorizedAccessAudit', 'RBAC_LANDING', 'Record unauthorized dashboard attempt.', 'accelerator-security', 'RBAC_LANDING', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-048', 'CreateRBACEvidenceEvent', 'RBAC_LANDING', 'Create evidence event for RBAC route decision.', 'accelerator-security', 'RBAC_LANDING', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-049', 'ValidateLogoutSession', 'LOGOUT', 'Validate logout session reference.', 'accelerator-security', 'LOGOUT', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-050', 'RevokeSession', 'LOGOUT', 'Revoke active session.', 'accelerator-security', 'LOGOUT', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-051', 'ClearSessionContext', 'LOGOUT', 'Clear local session context.', 'accelerator-security', 'LOGOUT', false, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-052', 'RecordLogoutAudit', 'LOGOUT', 'Record logout event.', 'accelerator-security', 'LOGOUT', true, true, false, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-053', 'CreateLogoutEvidenceEvent', 'LOGOUT', 'Create evidence event for logout.', 'accelerator-security', 'LOGOUT', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-054', 'CreateIdentityEvidenceRecord', 'EVIDENCE', 'Create standard identity evidence record.', 'accelerator-security', 'EVIDENCE', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-055', 'LinkEvidenceToIdentity', 'EVIDENCE', 'Link evidence event to identity.', 'accelerator-security', 'EVIDENCE', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-056', 'LinkEvidenceToInstitution', 'EVIDENCE', 'Link evidence event to institution.', 'accelerator-security', 'EVIDENCE', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-057', 'LinkEvidenceToAccessRequest', 'EVIDENCE', 'Link evidence event to access request.', 'accelerator-security', 'EVIDENCE', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

INSERT INTO aira_security.identity_microfunction_catalog
(microfunction_key, microfunction_name, microfunction_category, microfunction_description, owning_module, execution_phase, fail_closed_required, audit_required, evidence_required, microfunction_status)
VALUES ('MF-IDENTITY-058', 'ValidateEvidenceCompleteness', 'EVIDENCE', 'Validate required evidence exists for acceptance.', 'accelerator-security', 'EVIDENCE', true, true, true, 'ACTIVE')
ON CONFLICT (microfunction_key) DO UPDATE SET
    microfunction_name = EXCLUDED.microfunction_name,
    microfunction_category = EXCLUDED.microfunction_category,
    microfunction_description = EXCLUDED.microfunction_description,
    owning_module = EXCLUDED.owning_module,
    execution_phase = EXCLUDED.execution_phase,
    fail_closed_required = EXCLUDED.fail_closed_required,
    audit_required = EXCLUDED.audit_required,
    evidence_required = EXCLUDED.evidence_required,
    microfunction_status = EXCLUDED.microfunction_status,
    updated_at = NOW();

-- POC-1 Phase 1 readiness marker
INSERT INTO aira_security.identity_login_audit
(normalized_email, event_type, event_result, denial_reason, client_ip, user_agent)
VALUES ('poc1.phase1@aira.local', 'POC1_PHASE1_IDENTITY_DATABASE_SEEDED', 'ALLOWED', NULL, 'local-build', 'AIRA-POC1-BUILD-PHASE1')
ON CONFLICT DO NOTHING;